/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as QuantumRouteImport } from './routes/quantum'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as FusionRouteImport } from './routes/fusion'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettlementRouteImport } from './routes/_authenticated/settlement'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResellerKeysRouteImport } from './routes/_authenticated/reseller-keys'
import { Route as AuthenticatedResellerAdminRouteImport } from './routes/_authenticated/reseller-admin'
import { Route as AuthenticatedResellerRouteImport } from './routes/_authenticated/reseller'
import { Route as AuthenticatedRedemptionRouteImport } from './routes/_authenticated/redemption'
import { Route as AuthenticatedPromoAdsRouteImport } from './routes/_authenticated/promo-ads'
import { Route as AuthenticatedProfitRouteImport } from './routes/_authenticated/profit'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlatformSettingsRouteImport } from './routes/_authenticated/platform-settings'
import { Route as AuthenticatedPasswordRouteImport } from './routes/_authenticated/password'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedNotFoundRouteImport } from './routes/_authenticated/not-found'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedMenuPermissionsRouteImport } from './routes/_authenticated/menu-permissions'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedDistributorsRouteImport } from './routes/_authenticated/distributors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authChatRouteImport } from './routes/(auth)/chat'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantumRoute = QuantumRouteImport.update({
  id: '/quantum',
  path: '/quantum',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const FusionRoute = FusionRouteImport.update({
  id: '/fusion',
  path: '/fusion',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettlementRoute = AuthenticatedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResellerKeysRoute =
  AuthenticatedResellerKeysRouteImport.update({
    id: '/reseller-keys',
    path: '/reseller-keys',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerAdminRoute =
  AuthenticatedResellerAdminRouteImport.update({
    id: '/reseller-admin',
    path: '/reseller-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResellerRoute = AuthenticatedResellerRouteImport.update({
  id: '/reseller',
  path: '/reseller',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedemptionRoute = AuthenticatedRedemptionRouteImport.update({
  id: '/redemption',
  path: '/redemption',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromoAdsRoute = AuthenticatedPromoAdsRouteImport.update({
  id: '/promo-ads',
  path: '/promo-ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitRoute = AuthenticatedProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformSettingsRoute =
  AuthenticatedPlatformSettingsRouteImport.update({
    id: '/platform-settings',
    path: '/platform-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPasswordRoute = AuthenticatedPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotFoundRoute = AuthenticatedNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuPermissionsRoute =
  AuthenticatedMenuPermissionsRouteImport.update({
    id: '/menu-permissions',
    path: '/menu-permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistributorsRoute =
  AuthenticatedDistributorsRouteImport.update({
    id: '/distributors',
    path: '/distributors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authChatRoute = authChatRouteImport.update({
  id: '/(auth)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/enterprise': typeof EnterpriseRoute
  '/fusion': typeof FusionRoute
  '/models': typeof ModelsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quantum': typeof QuantumRoute
  '/rankings': typeof RankingsRoute
  '/chat': typeof authChatRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributors': typeof AuthenticatedDistributorsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/menu-permissions': typeof AuthenticatedMenuPermissionsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/news': typeof AuthenticatedNewsRoute
  '/not-found': typeof AuthenticatedNotFoundRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/promo-ads': typeof AuthenticatedPromoAdsRoute
  '/redemption': typeof AuthenticatedRedemptionRoute
  '/reseller': typeof AuthenticatedResellerRoute
  '/reseller-admin': typeof AuthenticatedResellerAdminRoute
  '/reseller-keys': typeof AuthenticatedResellerKeysRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/enterprise': typeof EnterpriseRoute
  '/fusion': typeof FusionRoute
  '/models': typeof ModelsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quantum': typeof QuantumRoute
  '/rankings': typeof RankingsRoute
  '/chat': typeof authChatRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributors': typeof AuthenticatedDistributorsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/menu-permissions': typeof AuthenticatedMenuPermissionsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/news': typeof AuthenticatedNewsRoute
  '/not-found': typeof AuthenticatedNotFoundRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/password': typeof AuthenticatedPasswordRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/promo-ads': typeof AuthenticatedPromoAdsRoute
  '/redemption': typeof AuthenticatedRedemptionRoute
  '/reseller': typeof AuthenticatedResellerRoute
  '/reseller-admin': typeof AuthenticatedResellerAdminRoute
  '/reseller-keys': typeof AuthenticatedResellerKeysRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlement': typeof AuthenticatedSettlementRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/enterprise': typeof EnterpriseRoute
  '/fusion': typeof FusionRoute
  '/models': typeof ModelsRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/playground': typeof PlaygroundRoute
  '/pricing': typeof PricingRoute
  '/quantum': typeof QuantumRoute
  '/rankings': typeof RankingsRoute
  '/(auth)/chat': typeof authChatRoute
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distributors': typeof AuthenticatedDistributorsRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/menu-permissions': typeof AuthenticatedMenuPermissionsRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/not-found': typeof AuthenticatedNotFoundRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/password': typeof AuthenticatedPasswordRoute
  '/_authenticated/platform-settings': typeof AuthenticatedPlatformSettingsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/profit': typeof AuthenticatedProfitRoute
  '/_authenticated/promo-ads': typeof AuthenticatedPromoAdsRoute
  '/_authenticated/redemption': typeof AuthenticatedRedemptionRoute
  '/_authenticated/reseller': typeof AuthenticatedResellerRoute
  '/_authenticated/reseller-admin': typeof AuthenticatedResellerAdminRoute
  '/_authenticated/reseller-keys': typeof AuthenticatedResellerKeysRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/settlement': typeof AuthenticatedSettlementRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/enterprise'
    | '/fusion'
    | '/models'
    | '/oauth-callback'
    | '/playground'
    | '/pricing'
    | '/quantum'
    | '/rankings'
    | '/chat'
    | '/setup'
    | '/sign-in'
    | '/about'
    | '/admin-tools'
    | '/api-docs'
    | '/billing'
    | '/channels'
    | '/checkin'
    | '/connections'
    | '/dashboard'
    | '/distributors'
    | '/keys'
    | '/logs'
    | '/menu-permissions'
    | '/monitoring'
    | '/news'
    | '/not-found'
    | '/notifications'
    | '/password'
    | '/platform-settings'
    | '/profile'
    | '/profit'
    | '/promo-ads'
    | '/redemption'
    | '/reseller'
    | '/reseller-admin'
    | '/reseller-keys'
    | '/settings'
    | '/settlement'
    | '/subscription'
    | '/tasks'
    | '/team'
    | '/transactions'
    | '/users'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/enterprise'
    | '/fusion'
    | '/models'
    | '/oauth-callback'
    | '/playground'
    | '/pricing'
    | '/quantum'
    | '/rankings'
    | '/chat'
    | '/setup'
    | '/sign-in'
    | '/about'
    | '/admin-tools'
    | '/api-docs'
    | '/billing'
    | '/channels'
    | '/checkin'
    | '/connections'
    | '/dashboard'
    | '/distributors'
    | '/keys'
    | '/logs'
    | '/menu-permissions'
    | '/monitoring'
    | '/news'
    | '/not-found'
    | '/notifications'
    | '/password'
    | '/platform-settings'
    | '/profile'
    | '/profit'
    | '/promo-ads'
    | '/redemption'
    | '/reseller'
    | '/reseller-admin'
    | '/reseller-keys'
    | '/settings'
    | '/settlement'
    | '/subscription'
    | '/tasks'
    | '/team'
    | '/transactions'
    | '/users'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/apps'
    | '/enterprise'
    | '/fusion'
    | '/models'
    | '/oauth-callback'
    | '/playground'
    | '/pricing'
    | '/quantum'
    | '/rankings'
    | '/(auth)/chat'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/_authenticated/about'
    | '/_authenticated/admin-tools'
    | '/_authenticated/api-docs'
    | '/_authenticated/billing'
    | '/_authenticated/channels'
    | '/_authenticated/checkin'
    | '/_authenticated/connections'
    | '/_authenticated/dashboard'
    | '/_authenticated/distributors'
    | '/_authenticated/keys'
    | '/_authenticated/logs'
    | '/_authenticated/menu-permissions'
    | '/_authenticated/monitoring'
    | '/_authenticated/news'
    | '/_authenticated/not-found'
    | '/_authenticated/notifications'
    | '/_authenticated/password'
    | '/_authenticated/platform-settings'
    | '/_authenticated/profile'
    | '/_authenticated/profit'
    | '/_authenticated/promo-ads'
    | '/_authenticated/redemption'
    | '/_authenticated/reseller'
    | '/_authenticated/reseller-admin'
    | '/_authenticated/reseller-keys'
    | '/_authenticated/settings'
    | '/_authenticated/settlement'
    | '/_authenticated/subscription'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/transactions'
    | '/_authenticated/users'
    | '/_authenticated/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  FusionRoute: typeof FusionRoute
  ModelsRoute: typeof ModelsRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PricingRoute: typeof PricingRoute
  QuantumRoute: typeof QuantumRoute
  RankingsRoute: typeof RankingsRoute
  authChatRoute: typeof authChatRoute
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantum': {
      id: '/quantum'
      path: '/quantum'
      fullPath: '/quantum'
      preLoaderRoute: typeof QuantumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fusion': {
      id: '/fusion'
      path: '/fusion'
      fullPath: '/fusion'
      preLoaderRoute: typeof FusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settlement': {
      id: '/_authenticated/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof AuthenticatedSettlementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-keys': {
      id: '/_authenticated/reseller-keys'
      path: '/reseller-keys'
      fullPath: '/reseller-keys'
      preLoaderRoute: typeof AuthenticatedResellerKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller-admin': {
      id: '/_authenticated/reseller-admin'
      path: '/reseller-admin'
      fullPath: '/reseller-admin'
      preLoaderRoute: typeof AuthenticatedResellerAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reseller': {
      id: '/_authenticated/reseller'
      path: '/reseller'
      fullPath: '/reseller'
      preLoaderRoute: typeof AuthenticatedResellerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redemption': {
      id: '/_authenticated/redemption'
      path: '/redemption'
      fullPath: '/redemption'
      preLoaderRoute: typeof AuthenticatedRedemptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promo-ads': {
      id: '/_authenticated/promo-ads'
      path: '/promo-ads'
      fullPath: '/promo-ads'
      preLoaderRoute: typeof AuthenticatedPromoAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profit': {
      id: '/_authenticated/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof AuthenticatedProfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings': {
      id: '/_authenticated/platform-settings'
      path: '/platform-settings'
      fullPath: '/platform-settings'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/password': {
      id: '/_authenticated/password'
      path: '/password'
      fullPath: '/password'
      preLoaderRoute: typeof AuthenticatedPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/not-found': {
      id: '/_authenticated/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof AuthenticatedNotFoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu-permissions': {
      id: '/_authenticated/menu-permissions'
      path: '/menu-permissions'
      fullPath: '/menu-permissions'
      preLoaderRoute: typeof AuthenticatedMenuPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distributors': {
      id: '/_authenticated/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof AuthenticatedDistributorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/chat': {
      id: '/(auth)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof authChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributorsRoute: typeof AuthenticatedDistributorsRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMenuPermissionsRoute: typeof AuthenticatedMenuPermissionsRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNotFoundRoute: typeof AuthenticatedNotFoundRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPasswordRoute: typeof AuthenticatedPasswordRoute
  AuthenticatedPlatformSettingsRoute: typeof AuthenticatedPlatformSettingsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProfitRoute: typeof AuthenticatedProfitRoute
  AuthenticatedPromoAdsRoute: typeof AuthenticatedPromoAdsRoute
  AuthenticatedRedemptionRoute: typeof AuthenticatedRedemptionRoute
  AuthenticatedResellerRoute: typeof AuthenticatedResellerRoute
  AuthenticatedResellerAdminRoute: typeof AuthenticatedResellerAdminRoute
  AuthenticatedResellerKeysRoute: typeof AuthenticatedResellerKeysRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSettlementRoute: typeof AuthenticatedSettlementRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributorsRoute: AuthenticatedDistributorsRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMenuPermissionsRoute: AuthenticatedMenuPermissionsRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNotFoundRoute: AuthenticatedNotFoundRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPasswordRoute: AuthenticatedPasswordRoute,
  AuthenticatedPlatformSettingsRoute: AuthenticatedPlatformSettingsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProfitRoute: AuthenticatedProfitRoute,
  AuthenticatedPromoAdsRoute: AuthenticatedPromoAdsRoute,
  AuthenticatedRedemptionRoute: AuthenticatedRedemptionRoute,
  AuthenticatedResellerRoute: AuthenticatedResellerRoute,
  AuthenticatedResellerAdminRoute: AuthenticatedResellerAdminRoute,
  AuthenticatedResellerKeysRoute: AuthenticatedResellerKeysRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSettlementRoute: AuthenticatedSettlementRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  EnterpriseRoute: EnterpriseRoute,
  FusionRoute: FusionRoute,
  ModelsRoute: ModelsRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlaygroundRoute: PlaygroundRoute,
  PricingRoute: PricingRoute,
  QuantumRoute: QuantumRoute,
  RankingsRoute: RankingsRoute,
  authChatRoute: authChatRoute,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
