/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRedemptionRouteImport } from './routes/_authenticated/redemption'
import { Route as AuthenticatedProfitRouteImport } from './routes/_authenticated/profit'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlaygroundRouteImport } from './routes/_authenticated/playground'
import { Route as AuthenticatedNotFoundRouteImport } from './routes/_authenticated/not-found'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedDistributorsRouteImport } from './routes/_authenticated/distributors'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedChannelsRouteImport } from './routes/_authenticated/channels'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApiDocsRouteImport } from './routes/_authenticated/api-docs'
import { Route as AuthenticatedAdminToolsRouteImport } from './routes/_authenticated/admin-tools'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSetupRouteImport } from './routes/(auth)/setup'
import { Route as authChatRouteImport } from './routes/(auth)/chat'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedemptionRoute = AuthenticatedRedemptionRouteImport.update({
  id: '/redemption',
  path: '/redemption',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfitRoute = AuthenticatedProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaygroundRoute = AuthenticatedPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotFoundRoute = AuthenticatedNotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistributorsRoute =
  AuthenticatedDistributorsRouteImport.update({
    id: '/distributors',
    path: '/distributors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChannelsRoute = AuthenticatedChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiDocsRoute = AuthenticatedApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminToolsRoute = AuthenticatedAdminToolsRouteImport.update({
  id: '/admin-tools',
  path: '/admin-tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSetupRoute = authSetupRouteImport.update({
  id: '/(auth)/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const authChatRoute = authChatRouteImport.update({
  id: '/(auth)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof authChatRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributors': typeof AuthenticatedDistributorsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/news': typeof AuthenticatedNewsRoute
  '/not-found': typeof AuthenticatedNotFoundRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/redemption': typeof AuthenticatedRedemptionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof authChatRoute
  '/setup': typeof authSetupRoute
  '/sign-in': typeof authSignInRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/api-docs': typeof AuthenticatedApiDocsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/channels': typeof AuthenticatedChannelsRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distributors': typeof AuthenticatedDistributorsRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/models': typeof AuthenticatedModelsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/news': typeof AuthenticatedNewsRoute
  '/not-found': typeof AuthenticatedNotFoundRoute
  '/playground': typeof AuthenticatedPlaygroundRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/profit': typeof AuthenticatedProfitRoute
  '/redemption': typeof AuthenticatedRedemptionRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/users': typeof AuthenticatedUsersRoute
  '/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/chat': typeof authChatRoute
  '/(auth)/setup': typeof authSetupRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin-tools': typeof AuthenticatedAdminToolsRoute
  '/_authenticated/api-docs': typeof AuthenticatedApiDocsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distributors': typeof AuthenticatedDistributorsRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/not-found': typeof AuthenticatedNotFoundRoute
  '/_authenticated/playground': typeof AuthenticatedPlaygroundRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/profit': typeof AuthenticatedProfitRoute
  '/_authenticated/redemption': typeof AuthenticatedRedemptionRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/setup'
    | '/sign-in'
    | '/about'
    | '/admin-tools'
    | '/api-docs'
    | '/billing'
    | '/channels'
    | '/checkin'
    | '/dashboard'
    | '/distributors'
    | '/keys'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/news'
    | '/not-found'
    | '/playground'
    | '/profile'
    | '/profit'
    | '/redemption'
    | '/settings'
    | '/subscription'
    | '/tasks'
    | '/users'
    | '/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/setup'
    | '/sign-in'
    | '/about'
    | '/admin-tools'
    | '/api-docs'
    | '/billing'
    | '/channels'
    | '/checkin'
    | '/dashboard'
    | '/distributors'
    | '/keys'
    | '/logs'
    | '/models'
    | '/monitoring'
    | '/news'
    | '/not-found'
    | '/playground'
    | '/profile'
    | '/profit'
    | '/redemption'
    | '/settings'
    | '/subscription'
    | '/tasks'
    | '/users'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/chat'
    | '/(auth)/setup'
    | '/(auth)/sign-in'
    | '/_authenticated/about'
    | '/_authenticated/admin-tools'
    | '/_authenticated/api-docs'
    | '/_authenticated/billing'
    | '/_authenticated/channels'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/distributors'
    | '/_authenticated/keys'
    | '/_authenticated/logs'
    | '/_authenticated/models'
    | '/_authenticated/monitoring'
    | '/_authenticated/news'
    | '/_authenticated/not-found'
    | '/_authenticated/playground'
    | '/_authenticated/profile'
    | '/_authenticated/profit'
    | '/_authenticated/redemption'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/tasks'
    | '/_authenticated/users'
    | '/_authenticated/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authChatRoute: typeof authChatRoute
  authSetupRoute: typeof authSetupRoute
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redemption': {
      id: '/_authenticated/redemption'
      path: '/redemption'
      fullPath: '/redemption'
      preLoaderRoute: typeof AuthenticatedRedemptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profit': {
      id: '/_authenticated/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof AuthenticatedProfitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playground': {
      id: '/_authenticated/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AuthenticatedPlaygroundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/not-found': {
      id: '/_authenticated/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof AuthenticatedNotFoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distributors': {
      id: '/_authenticated/distributors'
      path: '/distributors'
      fullPath: '/distributors'
      preLoaderRoute: typeof AuthenticatedDistributorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-docs': {
      id: '/_authenticated/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof AuthenticatedApiDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tools': {
      id: '/_authenticated/admin-tools'
      path: '/admin-tools'
      fullPath: '/admin-tools'
      preLoaderRoute: typeof AuthenticatedAdminToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/setup': {
      id: '/(auth)/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof authSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/chat': {
      id: '/(auth)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof authChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminToolsRoute: typeof AuthenticatedAdminToolsRoute
  AuthenticatedApiDocsRoute: typeof AuthenticatedApiDocsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChannelsRoute: typeof AuthenticatedChannelsRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributorsRoute: typeof AuthenticatedDistributorsRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedNotFoundRoute: typeof AuthenticatedNotFoundRoute
  AuthenticatedPlaygroundRoute: typeof AuthenticatedPlaygroundRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProfitRoute: typeof AuthenticatedProfitRoute
  AuthenticatedRedemptionRoute: typeof AuthenticatedRedemptionRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminToolsRoute: AuthenticatedAdminToolsRoute,
  AuthenticatedApiDocsRoute: AuthenticatedApiDocsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChannelsRoute: AuthenticatedChannelsRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributorsRoute: AuthenticatedDistributorsRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedNotFoundRoute: AuthenticatedNotFoundRoute,
  AuthenticatedPlaygroundRoute: AuthenticatedPlaygroundRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProfitRoute: AuthenticatedProfitRoute,
  AuthenticatedRedemptionRoute: AuthenticatedRedemptionRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authChatRoute: authChatRoute,
  authSetupRoute: authSetupRoute,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
