package channeltype

// ChannelTypeNames — 所有渠道类型的名称映射
// key = channelType int, value = 显示名称（英文技术标识符）
// 前端通过 GET /api/channel/types 动态获取，避免硬编码
var ChannelTypeNames = map[int]string{
	// ==================== AI 大模型渠道 (0~61) ====================
	Unknown:              "Unknown",
	OpenAI:               "OpenAI",
	API2D:                "API2D",
	Azure:                "Azure",
	CloseAI:              "CloseAI",
	OpenAISB:             "OpenAI SB",
	OpenAIMax:            "OpenAI Max",
	OhMyGPT:              "OhMyGPT",
	Custom:               "Custom",
	Ails:                 "Ails",
	AIProxy:              "AI Proxy",
	PaLM:                 "Google PaLM",
	API2GPT:              "API2GPT",
	AIGC2D:               "AIGC2D",
	Anthropic:            "Anthropic",
	Baidu:                "Baidu",
	Zhipu:                "Zhipu (GLM)",
	Ali:                  "Ali (Qwen)",
	Xunfei:               "Xunfei (Spark)",
	AI360:                "360 AI",
	QuantumClaw:           "API Relay",
	AIProxyLibrary:       "AIProxy Library",
	FastGPT:              "FastGPT",
	Tencent:              "Tencent (Hunyuan)",
	Gemini:               "Google Gemini",
	Moonshot:             "Moonshot (Kimi)",
	Baichuan:             "Baichuan",
	Minimax:              "MiniMax",
	Mistral:              "Mistral AI",
	Groq:                 "Groq",
	Ollama:               "Ollama",
	LingYiWanWu:          "LingYi (01.AI)",
	StepFun:              "StepFun (Step-2)",
	AwsClaude:            "AWS Claude",
	Coze:                 "Coze",
	Cohere:               "Cohere",
	DeepSeek:             "DeepSeek",
	Cloudflare:           "Cloudflare",
	DeepL:                "DeepL",
	TogetherAI:           "Together AI",
	Doubao:               "Doubao (VolcEngine)",
	Novita:               "Novita AI",
	VertextAI:            "Google Vertex AI",
	Proxy:                "Proxy",
	SiliconFlow:          "SiliconFlow",
	XAI:                  "xAI (Grok)",
	Replicate:            "Replicate",
	BaiduV2:              "Baidu V2",
	XunfeiV2:             "Xunfei V2",
	AliBailian:           "Ali Bailian",
	OpenAICompatible:     "OpenAI Compatible",
	GeminiOpenAICompatible: "Gemini OpenAI Compatible",
	Codex:                "Codex",
	Dify:                 "Dify",
	Jimeng:               "Jimeng",
	Jina:                 "Jina AI",
	MokaAI:               "Moka AI",
	Submodel:             "Submodel",
	VolcEngine:           "VolcEngine (Ark)",
	Xinference:           "Xinference",
	ZhipuV4:              "Zhipu V4",

	// ==================== 量子算力渠道 (type >= 100) ====================
	IonQ:         "IonQ",
	IBMQ:         "IBM Q",
	Rigetti:      "Rigetti",
	AWSBraket:    "AWS Braket",
	AzureQuantum: "Azure Quantum",
	GoogleQuantum: "Google Quantum",
}
