#!/bin/bash
# ============================================================
# BaoTa Panel One-Click Deployment Script for QuantumClaw
# Supports Ubuntu/Debian/CentOS with BaoTa panel
# ============================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Default values
INSTALL_DIR="/opt/quantumclaw"
COMPOSE_FILE="docker-compose.sqlite.yml"
DOMAIN=""
DB_TYPE="sqlite"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --dir) INSTALL_DIR="$2"; shift 2 ;;
        --domain) DOMAIN="$2"; shift 2 ;;
        --db-type)
            case "$2" in
                sqlite|mysql) DB_TYPE="$2";;
                *) log_error "Unsupported DB type: $2 (use sqlite or mysql)"; exit 1;;
            esac
            shift 2 ;;
        --help)
            echo "Usage: $0 [options]"
            echo "Options:"
            echo "  --dir DIR        Installation directory (default: /opt/quantumclaw)"
            echo "  --domain DOMAIN  Domain name for reverse proxy"
            echo "  --db-type TYPE   Database type: sqlite or mysql (default: sqlite)"
            exit 0 ;;
        *) log_error "Unknown option: $1"; exit 1 ;;
    esac
done

# Check root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

# Check OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    OS=$(uname -s)
fi

log_info "Detected OS: $OS"

# Install Docker if not present
check_docker() {
    if ! command -v docker &> /dev/null; then
        log_info "Docker not found, installing..."
        case $OS in
            ubuntu|debian)
                apt-get update -qq
                apt-get install -y -qq ca-certificates curl
                install -m 0755 -d /etc/apt/keyrings
                curl -fsSL https://download.docker.com/linux/$OS/gpg -o /etc/apt/keyrings/docker.asc
                chmod a+r /etc/apt/keyrings/docker.asc
                echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/$OS $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
                apt-get update -qq
                apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
                ;;
            centos|rocky|almalinux)
                yum install -y yum-utils
                yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
                yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
                ;;
            *)
                log_error "Unsupported OS for automatic Docker installation: $OS"
                log_error "Please install Docker manually: https://docs.docker.com/engine/install/"
                exit 1
                ;;
        esac
        systemctl enable --now docker
        log_info "Docker installed successfully"
    else
        log_info "Docker already installed: $(docker --version)"
    fi

    if ! docker compose version &>/dev/null; then
        log_error "Docker Compose v2 plugin not found. Please install it."
        exit 1
    fi
}

# Create .env file
create_env() {
    local env_file="$INSTALL_DIR/.env"
    if [ -f "$env_file" ]; then
        log_warn ".env file already exists, backing up..."
        cp "$env_file" "${env_file}.bak.$(date +%Y%m%d%H%M%S)"
    fi

    log_info "Creating .env file..."
    cat > "$env_file" << 'EOF'
# ============================================================
# QuantumClaw - Generated by BaoTa deploy script
# ============================================================

# -----------------------
# Database
# -----------------------
SQLITE_PATH=./data/quantumclaw.db
SQLITE_BUSY_TIMEOUT=3000

# Redis
REDIS=redis:6379

# -----------------------
# App Settings
# -----------------------
PORT=3000
GIN_MODE=release
SESSION_SECRET=CHANGE_ME_TO_A_RANDOM_STRING
THEME=default

# Initial root token (change after first login!)
INITIAL_ROOT_TOKEN=quantumclaw-root-token
INITIAL_ROOT_ACCESS_TOKEN=quantumclaw-root-access-token

# Feature flags
MEMORY_CACHE_ENABLED=true
SYNC_FREQUENCY=600
BATCH_UPDATE_ENABLED=false
EOF

    if [ "$DB_TYPE" = "mysql" ]; then
        local mysql_pwd=$(openssl rand -base64 16 2>/dev/null || echo "quantumclaw")
        cat >> "$env_file" << EOF

# MySQL configuration
SQL_DSN=root:${mysql_pwd}@tcp(mysql:3306)/quantumclaw?charset=utf8mb4&parseTime=True&loc=Local
MYSQL_ROOT_PASSWORD=${mysql_pwd}
MYSQL_DATABASE=quantumclaw
MYSQL_USER=quantumclaw
MYSQL_PASSWORD=${mysql_pwd}
EOF
        COMPOSE_FILE="docker-compose.yml"
    fi

    log_info ".env file created: $env_file"
    log_warn "Please update SESSION_SECRET and INITIAL_ROOT_TOKEN in .env for security!"
}

# Clone or update QuantumClaw
clone_repo() {
    if [ -d "$INSTALL_DIR/code" ]; then
        log_info "Updating QuantumClaw..."
        cd "$INSTALL_DIR/code"
        git pull
    else
        log_info "Cloning QuantumClaw..."
        git clone https://github.com/quantumclaw/quantumclaw.git "$INSTALL_DIR/code"
    fi
}

# Copy docker-compose and create data dir
setup_files() {
    mkdir -p "$INSTALL_DIR/data"
    cp "$INSTALL_DIR/code/$COMPOSE_FILE" "$INSTALL_DIR/docker-compose.yml"
    cp "$INSTALL_DIR/code/.env.example" "$INSTALL_DIR/.env.example"
}

# Deploy with docker compose
deploy() {
    cd "$INSTALL_DIR"
    log_info "Pulling Docker images..."
    docker compose pull

    log_info "Starting QuantumClaw..."
    docker compose up -d

    log_info "Waiting for service to be ready..."
    sleep 5

    if docker compose ps | grep -q "Up"; then
        log_info "QuantumClaw is running!"
    else
        log_error "QuantumClaw failed to start. Check logs: docker compose logs"
        exit 1
    fi
}

# Configure Nginx reverse proxy (if domain provided)
setup_nginx() {
    if [ -z "$DOMAIN" ]; then
        return
    fi

    log_info "Setting up Nginx reverse proxy for $DOMAIN..."

    if ! command -v nginx &> /dev/null; then
        case $OS in
            ubuntu|debian) apt-get install -y -qq nginx ;;
            centos|rocky|almalinux) yum install -y nginx ;;
        esac
    fi

    cat > /etc/nginx/conf.d/quantumclaw.conf << NGINX
server {
    listen 80;
    server_name $DOMAIN;

    client_max_body_size 100m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;

        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
}
NGINX

    nginx -t && systemctl reload nginx
    log_info "Nginx configured for $DOMAIN"

    if command -v certbot &> /dev/null; then
        log_info "Obtaining SSL certificate..."
        certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --email "admin@$DOMAIN" || log_warn "SSL setup failed, you can run 'certbot --nginx -d $DOMAIN' manually"
    else
        log_info "certbot not found. To enable HTTPS:"
        log_info "  1. apt-get install certbot python3-certbot-nginx"
        log_info "  2. certbot --nginx -d $DOMAIN"
    fi
}

# Show completion message
show_summary() {
    echo ""
    echo "============================================"
    echo -e "${GREEN}  QuantumClaw deployed successfully!${NC}"
    echo "============================================"
    echo ""
    echo "  Installation directory: $INSTALL_DIR"
    echo ""
    if [ -n "$DOMAIN" ]; then
        echo "  Access: http://$DOMAIN"
    else
        echo "  Access: http://$(curl -s ifconfig.me 2>/dev/null || hostname -I | awk '{print $1}'):3000"
    fi
    echo ""
    echo "  First login:"
    echo "    Username: root"
    echo "    Password: 123456"
    echo ""
    echo "  Important: Change the default password immediately!"
    echo ""
    echo "  Commands:"
    echo "    cd $INSTALL_DIR"
    echo "    docker compose logs -f    # View logs"
    echo "    docker compose restart    # Restart"
    echo "    docker compose pull && docker compose up -d  # Update"
    echo ""
    echo "============================================"
}

# =================== Main ===================
echo ""
echo "============================================"
echo "  QuantumClaw One-Click Installer (BaoTa)"
echo "============================================"
echo ""

check_docker
create_env
clone_repo
setup_files
deploy
setup_nginx
show_summary
