// Package cascade defines the protocol contract between QuantumClaw master and slave nodes.
//
// Communication: HTTP REST over TLS.
// Authentication: X-Cascade-Key header (pre-shared API key, generated by master on node registration).
// Data format: JSON.
// Idempotency: all write operations carry idempotency_key to allow safe retries.
package cascade

// 
//  Node Registration & Heartbeat
// 

// RegisterRequest is sent by a slave node on startup.
type RegisterRequest struct {
	Name    string `json:"name"`    // e.g. "Tokyo-A"
	Region  string `json:"region"`  // e.g. "ap-northeast-1"
	Version string `json:"version"` // QuantumClaw version
}

// RegisterResponse is returned by the master after successful registration.
type RegisterResponse struct {
	NodeID int    `json:"node_id"`
	APIKey string `json:"api_key"` // one-time reveal; store locally on the slave
}

// HeartbeatRequest is sent periodically (every 30s) by the slave.
type HeartbeatRequest struct {
	NodeID       int     `json:"node_id"`
	LoadAvg      float64 `json:"load_avg"`
	ChannelCount int     `json:"channel_count"`
	TodayCalls   int64   `json:"today_calls"`
	UptimeSec    int64   `json:"uptime_sec"`
}

// HeartbeatResponse optionally carries pending work from master to slave.
type HeartbeatResponse struct {
	Status         string `json:"status"`          // "ok", "config_changed", "pending_sync"
	ConfigVersion  int64  `json:"config_version"`  // bump when global config changes
}

// 
//  Token Synchronisation (Master ?Slave)
// 

// TokenSyncRequest queries for tokens updated since a given timestamp.
type TokenSyncRequest struct {
	Since int64 `json:"since"` // unix timestamp; 0 = full sync
}

// TokenSyncItem is a minimal token representation for slave-side caching.
type TokenSyncItem struct {
	ID              int    `json:"id"`
	KeyHash         string `json:"key_hash"`
	UserID          int    `json:"user_id"`
	UserGroup       string `json:"user_group"`    // from user table, duplicated for offline auth
	UserStatus      int    `json:"user_status"`   // 1=enabled, 2=disabled
	Status          int    `json:"status"`        // 1=enabled, 2=disabled, 3=expired, 4=exhausted
	Models          string `json:"models"`        // comma-separated allowed models
	Subnet          string `json:"subnet"`
	RemainQuota     int64  `json:"remain_quota"`
	UnlimitedQuota  bool   `json:"unlimited_quota"`
	ExpiredTime     int64  `json:"expired_time"`
	UpdatedTime     int64  `json:"updated_time"`
}

// TokenSyncResponse carries the diff.
type TokenSyncResponse struct {
	Tokens  []TokenSyncItem `json:"tokens"`
	HasMore bool            `json:"has_more"`
}

// 
//  User Batch Query (Master ?Slave)
// 

// UserBatchRequest queries basic user info for a set of user IDs.
type UserBatchRequest struct {
	UserIDs []int `json:"user_ids"`
}

// UserBatchItem is a minimal user representation for slave-side auth.
type UserBatchItem struct {
	ID     int    `json:"id"`
	Group  string `json:"group"`
	Status int    `json:"status"` // 1=enabled
	Quota  int64  `json:"quota"`
}

type UserBatchResponse struct {
	Users []UserBatchItem `json:"users"`
}

// 
//  Billing Batch Push (Slave ?Master)
// 

// BillingRecord is a single deduction record created by a slave node.
// Multiple records are batched before pushing to the master.
type BillingRecord struct {
	IdempotencyKey  string `json:"idempotency_key"` // sha256(node_id + token_id + user_id + model + tokens + timestamp)
	TokenID         int    `json:"token_id"`
	UserID          int    `json:"user_id"`
	ChannelID       int    `json:"channel_id"`
	ModelName       string `json:"model_name"`
	PromptTokens    int    `json:"prompt_tokens"`
	CompletionTokens int   `json:"completion_tokens"`
	Quota           int64  `json:"quota"`  // amount deducted (pre-multiplied by ratio)
	PriceCents      int64  `json:"price_cents"`
	Timestamp       int64  `json:"timestamp"`
}

// BillingBatchRequest is sent by the slave to push accumulated billing records.
type BillingBatchRequest struct {
	NodeID      int              `json:"node_id"`
	BatchID     string           `json:"batch_id"` // UUID, unique per node
	Records     []BillingRecord  `json:"records"`
	TotalAmount int64            `json:"total_amount"` // sum(price_cents) for quick validation
}

// BillingBatchResponse tells the slave which records were accepted.
type BillingBatchResponse struct {
	Accepted int               `json:"accepted"`
	Rejected int               `json:"rejected"`
	Errors   []BillingError    `json:"errors,omitempty"`
}

// BillingError describes a single rejected record.
type BillingError struct {
	IdempotencyKey string `json:"idempotency_key"`
	Reason         string `json:"reason"`
}

// 
//  Global Config Sync (Master ?Slave)
// 

// ConfigSyncResponse carries the global configuration that every slave must honour.
type ConfigSyncResponse struct {
	Version          int64              `json:"version"`
	ModelRatios      map[string]float64 `json:"model_ratios"`
	CompletionRatios map[string]float64 `json:"completion_ratios"`
	ModelMapping     map[string]string  `json:"model_mapping"`
	Features         map[string]bool    `json:"features"` // e.g. {"enable_search":true}
	UpdatedAt        int64              `json:"updated_at"`
}
